In [2]:
import glob

files = glob.glob("*.csv")

print(files)

['air_reserve.csv', 'air_store_info.csv', 'air_visit_data.csv', 'date_info.csv', 'hpg_reserve.csv', 'hpg_store_info.csv', 'sample_submission.csv', 'store_id_relation.csv', 'total_dataset.csv', 'to_predict.csv', 'train.csv']

In [3]:
import pandas as pd

df = {}

for filename in files:
    df[filename.replace('.csv', '')] = pd.read_csv(filename)

print(df.keys())

dict_keys(['hpg_store_info', 'air_visit_data', 'to_predict', 'train', 'air_reserve', 'hpg_reserve', 'air_store_info', 'total_dataset', 'sample_submission', 'date_info', 'store_id_relation'])

In [3]:
print(len(pd.unique(df['store_id_relation']['air_store_id'])))
df['store_id_relation'].head()

150

           air_store_id          hpg_store_id
0  air_63b13c56b7201bd9  hpg_4bc649e72e2a239a
1  air_a24bf50c3e90d583  hpg_c34b496d0305a809
2  air_c7f78b4f3cba33ff  hpg_cd8ae0d9bbd58ff9
3  air_947eb2cae4f3e8f2  hpg_de24ea49dc25d6b8
4  air_965b2e0cf4119003  hpg_653238a84804d8e7

In [4]:
print(len(pd.unique(df['air_reserve']['air_store_id'])))
df['air_reserve'].head()

314

,air_store_id,visit_datetime,reserve_datetime,reserve_visitors
0,air_877f79706adbfb06,2016-01-01 19:00:00,2016-01-01 16:00:00,1
1,air_db4b38ebe7a7ceff,2016-01-01 19:00:00,2016-01-01 19:00:00,3
2,air_db4b38ebe7a7ceff,2016-01-01 19:00:00,2016-01-01 19:00:00,6
3,air_877f79706adbfb06,2016-01-01 20:00:00,2016-01-01 16:00:00,2
4,air_db80363d35f10926,2016-01-01 20:00:00,2016-01-01 01:00:00,5

In [5]:
print(len(df['air_store_info']))
df['air_store_info'].head()

829

,air_store_id,air_genre_name,air_area_name,latitude,longitude
0,air_0f0cdeee6c9bf3d7,Italian/French,Hyōgo-ken Kōbe-shi Kumoidōri,34.695124,135.197852
1,air_7cc17a324ae5c7dc,Italian/French,Hyōgo-ken Kōbe-shi Kumoidōri,34.695124,135.197852
2,air_fee8dcf4d619598e,Italian/French,Hyōgo-ken Kōbe-shi Kumoidōri,34.695124,135.197852
3,air_a17f0778617c76e2,Italian/French,Hyōgo-ken Kōbe-shi Kumoidōri,34.695124,135.197852
4,air_83db5aff8f50478e,Italian/French,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599

In [6]:
print(len(df['hpg_store_info']))
df['hpg_store_info'].head()

4690

,hpg_store_id,hpg_genre_name,hpg_area_name,latitude,longitude
0,hpg_6622b62385aec8bf,Japanese style,Tōkyō-to Setagaya-ku Taishidō,35.643675,139.668221
1,hpg_e9e068dd49c5fa00,Japanese style,Tōkyō-to Setagaya-ku Taishidō,35.643675,139.668221
2,hpg_2976f7acb4b3a3bc,Japanese style,Tōkyō-to Setagaya-ku Taishidō,35.643675,139.668221
3,hpg_e51a522e098f024c,Japanese style,Tōkyō-to Setagaya-ku Taishidō,35.643675,139.668221
4,hpg_e3d0e1519894f275,Japanese style,Tōkyō-to Setagaya-ku Taishidō,35.643675,139.668221

In [7]:
# Check if the 'air_store_info' contained all the 'air_store_id' needed for 'air_reserve'
check_air_reserve = pd.Series(pd.unique(df['air_reserve']['air_store_id'])).isin(df['air_store_info']['air_store_id'])
flag = True
for i in check_air_reserve:
    if i == False:
        print('False is found')
        flag = False
if flag == True:
    print('check successful, all the air_store_id in air_reserve could be found in air_store_info')

check successful, all the air_store_id in air_reserve could be found in air_store_info

In [8]:
# Check if the 'air_store_info' contained all the 'air_store_id' needed for 'store_id_relation'
# It turned out the 'air_store_info' contained all the infomation needed. The 'hpg_store_info' could be neglected.
check_air_reserve = pd.Series(pd.unique(df['store_id_relation']['air_store_id'])).isin(df['air_store_info']['air_store_id'])
flag = True
for i in check_air_reserve:
    if i == False:
        print('False is found')
        flag = False
if flag == True:
    print('check successful, all the air_store_id in store_id_relation could be found in air_store_info')

check successful, all the air_store_id in store_id_relation could be found in air_store_info

In [9]:
# Because the sample submission has no reservation information, so the reservation info from 'hpg_reserve' and 'air_reserve'
# is not very useful for predicting the visitors.

# print(len(pd.unique(df['hpg_reserve']['hpg_store_id'])))
# df['hpg_reserve'].head()

In [10]:
# hpg_reserve_merge = pd.merge(df['hpg_reserve'], df['store_id_relation'], how = 'left', on = 'hpg_store_id')
# air_reserve_on_hpg = hpg_reserve_merge.dropna(axis = 0).reset_index().drop(['hpg_store_id', 'index'], axis=1)
# air_reserve_on_hpg.head()

In [11]:
# len(pd.unique(air_reserve_on_hpg['air_store_id']))

In [12]:
# total_air_reserve = pd.concat([air_reserve_on_hpg, df['air_reserve']]).reset_index().drop(['index'], axis = 1)
# print(len(df['air_reserve']))
# print(len(air_reserve_on_hpg))
# print(len(total_air_reserve))
# total_air_reserve.head()

In [13]:
df['air_visit_data']['visit_datetime'] = pd.to_datetime(df['air_visit_data']['visit_date'])
df['air_visit_data']['visit_date'] = df['air_visit_data']['visit_datetime'].dt.date
# df['air_visit_data'].drop('visit_datetime', axis = 1, inplace = True)
df['air_visit_data'].head()

           air_store_id  visit_date  visitors visit_datetime
0  air_ba937bf13d40fb24  2016-01-13        25     2016-01-13
1  air_ba937bf13d40fb24  2016-01-14        32     2016-01-14
2  air_ba937bf13d40fb24  2016-01-15        29     2016-01-15
3  air_ba937bf13d40fb24  2016-01-16        22     2016-01-16
4  air_ba937bf13d40fb24  2016-01-18         6     2016-01-18

In [14]:
df['sample_submission']['visit_datetime'] = df['sample_submission']['id'].map(lambda x: str(x).split('_')[2])
df['sample_submission']['air_store_id'] = df['sample_submission']['id'].map(lambda x: '_'.join(x.split('_')[:2]))
df['sample_submission']['visit_datetime'] = pd.to_datetime(df['sample_submission']['visit_datetime'])
# df['sample_submission']['year'] = df['sample_submission']['visit_date'].dt.year
# df['sample_submission']['month'] = df['sample_submission']['visit_date'].dt.month
df['sample_submission']['visit_date'] = df['sample_submission']['visit_datetime'].dt.date
df['sample_submission'].drop(['id'], axis = 1, inplace = True)

df['sample_submission'].head()

   visitors visit_datetime          air_store_id  visit_date
0         0     2017-04-23  air_00a91d42b08b08d9  2017-04-23
1         0     2017-04-24  air_00a91d42b08b08d9  2017-04-24
2         0     2017-04-25  air_00a91d42b08b08d9  2017-04-25
3         0     2017-04-26  air_00a91d42b08b08d9  2017-04-26
4         0     2017-04-27  air_00a91d42b08b08d9  2017-04-27

In [15]:
total_dataset = pd.concat([df['air_visit_data'], df['sample_submission']], axis = 0)
print(len(df['air_visit_data']))
print(len(df['sample_submission']))
print(len(total_dataset))
total_dataset.head()

252108
32019
284127

           air_store_id  visit_date visit_datetime  visitors
0  air_ba937bf13d40fb24  2016-01-13     2016-01-13        25
1  air_ba937bf13d40fb24  2016-01-14     2016-01-14        32
2  air_ba937bf13d40fb24  2016-01-15     2016-01-15        29
3  air_ba937bf13d40fb24  2016-01-16     2016-01-16        22
4  air_ba937bf13d40fb24  2016-01-18     2016-01-18         6

In [16]:
# total_air_reserve['res_visit_datetime'] = pd.to_datetime(total_air_reserve['visit_datetime'])
# total_air_reserve['reserve_datetime'] = pd.to_datetime(total_air_reserve['reserve_datetime'])
# total_air_reserve['visit_date'] = total_air_reserve['res_visit_datetime'].dt.date
# total_air_reserve['reserve_diff'] = total_air_reserve.apply(lambda a: (a['res_visit_datetime']- a['reserve_datetime']).days, axis=1)
# total_air_reserve.drop('visit_datetime',  axis = 1, inplace=True)
# total_air_reserve.drop('reserve_datetime',  axis = 1, inplace=True)
# total_air_reserve.drop('res_visit_datetime',  axis = 1, inplace=True)
# print(len(total_air_reserve))
# total_air_reserve.head()

In [17]:
# avg_reserv = total_air_reserve.groupby(['air_store_id','visit_date'],as_index=False).mean().reset_index()
# total_air_reserve = total_air_reserve.groupby(['air_store_id','visit_date'],as_index=False).sum().reset_index().drop(['reserve_diff', 'index'], axis = 1)
# total_air_reserve['reserve_diff'] = avg_reserv['reserve_diff']
# print(len(total_air_reserve))
# total_air_reserve.head()

In [18]:
df['date_info']['calendar_date'] = pd.to_datetime(df['date_info']['calendar_date'])
df['date_info']['visit_date'] = df['date_info']['calendar_date'].dt.date
df['date_info'] = df['date_info'].drop(['calendar_date'], axis = 1)
df['date_info'].head()

  day_of_week  holiday_flg  visit_date
0      Friday            1  2016-01-01
1    Saturday            1  2016-01-02
2      Sunday            1  2016-01-03
3      Monday            0  2016-01-04
4     Tuesday            0  2016-01-05

In [19]:
total_dataset = pd.merge(total_dataset, df['air_store_info'], how='left', on='air_store_id')
total_dataset = pd.merge(total_dataset, df['date_info'], how='left', on='visit_date')
total_dataset.head()

,air_store_id,visit_date,visit_datetime,visitors,air_genre_name,air_area_name,latitude,longitude,day_of_week,holiday_flg
0,air_ba937bf13d40fb24,2016-01-13,2016-01-13,25,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,Wednesday,0
1,air_ba937bf13d40fb24,2016-01-14,2016-01-14,32,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,Thursday,0
2,air_ba937bf13d40fb24,2016-01-15,2016-01-15,29,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,Friday,0
3,air_ba937bf13d40fb24,2016-01-16,2016-01-16,22,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,Saturday,0
4,air_ba937bf13d40fb24,2016-01-18,2016-01-18,6,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,Monday,0

In [20]:
total_dataset['visit_datetime'] = pd.to_datetime(total_dataset['visit_date'])
# total_dataset['visit_datetime']

In [21]:
total_dataset['year']  = total_dataset['visit_datetime'].dt.year
total_dataset['month'] = total_dataset['visit_datetime'].dt.month
total_dataset['day']   = total_dataset['visit_datetime'].dt.day
total_dataset.drop('visit_datetime', axis=1, inplace=True)

# One Hot Encoding Conversion use the pandas.get_dummies
# https://pandas.pydata.org/pandas-docs/stable/generated/pandas.get_dummies.html

cat_features = [col for col in ['air_genre_name', 'air_area_name', 'day_of_week', 'year']]
for column in cat_features:
    temp = pd.get_dummies(pd.Series(total_dataset[column]))
    total_dataset = pd.concat([total_dataset,temp],axis=1)
    total_dataset = total_dataset.drop([column],axis=1)
    
total_dataset.head()

,air_store_id,visit_date,visitors,latitude,longitude,holiday_flg,month,day,Asian,Bar/Cocktail,...,Ōsaka-fu Ōsaka-shi Ōhiraki,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday,2016,2017
0,air_ba937bf13d40fb24,2016-01-13,25,35.658068,139.751599,0,1,13,0,0,...,0,0,0,0,0,0,0,1,1,0
1,air_ba937bf13d40fb24,2016-01-14,32,35.658068,139.751599,0,1,14,0,0,...,0,0,0,0,0,1,0,0,1,0
2,air_ba937bf13d40fb24,2016-01-15,29,35.658068,139.751599,0,1,15,0,0,...,0,1,0,0,0,0,0,0,1,0
3,air_ba937bf13d40fb24,2016-01-16,22,35.658068,139.751599,0,1,16,0,0,...,0,0,0,1,0,0,0,0,1,0
4,air_ba937bf13d40fb24,2016-01-18,6,35.658068,139.751599,0,1,18,0,0,...,0,0,1,0,0,0,0,0,1,0

In [22]:
# The method of clustering the locations of the restaurants was from 'Clustering to Reduce Spatial Data Set Size'
# http://geoffboeing.com/2014/08/clustering-to-reduce-spatial-data-set-size/


import pandas as pd, numpy as np, matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN
#from geopy.distance import great_circle
#from shapely.geometry import MultiPoint

coords =total_dataset.as_matrix(columns=['latitude', 'longitude'])
#coords = total_dataset.as_matrix(columns=['latitude', 'longitude'])
#pd.unique(total_dataset['latitude', 'longitude'])
print(len(coords))

284127

In [ ]:
kms_per_radian = 6371.0088
epsilon = 1.5 / kms_per_radian
db = DBSCAN(eps=epsilon, min_samples=3000, algorithm='ball_tree', metric='haversine').fit(np.radians(coords))
cluster_labels = db.labels_
num_clusters = len(set(cluster_labels))
clusters = pd.Series([coords[cluster_labels == n] for n in range(num_clusters)])
print('Number of clusters: {}'.format(num_clusters))
print(len(cluster_labels))

MemoryError:

In [92]:
# One Hot Encoding Conversion use the pandas.get_dummies
# https://pandas.pydata.org/pandas-docs/stable/generated/pandas.get_dummies.html
    
total_dataset = pd.concat([total_dataset, pd.get_dummies(cluster_labels, prefix='loc')], axis = 1)
total_dataset.drop(['latitude', 'longitude'], axis = 1, inplace = True)
total_dataset

,air_store_id,visit_date,visitors,holiday_flg,month,day,Asian,Bar/Cocktail,Cafe/Sweets,Creative cuisine,...,loc_14,loc_15,loc_16,loc_17,loc_18,loc_19,loc_20,loc_21,loc_22,loc_23
0,air_ba937bf13d40fb24,2016-01-13,25,0,1,13,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,air_ba937bf13d40fb24,2016-01-14,32,0,1,14,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,air_ba937bf13d40fb24,2016-01-15,29,0,1,15,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,air_ba937bf13d40fb24,2016-01-16,22,0,1,16,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,air_ba937bf13d40fb24,2016-01-18,6,0,1,18,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,air_ba937bf13d40fb24,2016-01-19,9,0,1,19,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,air_ba937bf13d40fb24,2016-01-20,31,0,1,20,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,air_ba937bf13d40fb24,2016-01-21,21,0,1,21,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,air_ba937bf13d40fb24,2016-01-22,18,0,1,22,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,air_ba937bf13d40fb24,2016-01-23,26,0,1,23,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,air_ba937bf13d40fb24,2016-01-25,21,0,1,25,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,air_ba937bf13d40fb24,2016-01-26,11,0,1,26,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,air_ba937bf13d40fb24,2016-01-27,24,0,1,27,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,air_ba937bf13d40fb24,2016-01-28,21,0,1,28,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,air_ba937bf13d40fb24,2016-01-29,26,0,1,29,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,air_ba937bf13d40fb24,2016-01-30,6,0,1,30,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,air_ba937bf13d40fb24,2016-02-03,18,0,2,3,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,air_ba937bf13d40fb24,2016-02-04,12,0,2,4,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,air_ba937bf13d40fb24,2016-02-05,45,0,2,5,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,air_ba937bf13d40fb24,2016-02-06,15,0,2,6,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,air_ba937bf13d40fb24,2016-02-08,19,0,2,8,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,air_ba937bf13d40fb24,2016-02-09,15,0,2,9,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,air_ba937bf13d40fb24,2016-02-10,32,0,2,10,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,air_ba937bf13d40fb24,2016-02-11,3,1,2,11,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,air_ba937bf13d40fb24,2016-02-12,26,0,2,12,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,air_ba937bf13d40fb24,2016-02-13,8,0,2,13,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,air_ba937bf13d40fb24,2016-02-15,14,0,2,15,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,air_ba937bf13d40fb24,2016-02-16,15,0,2,16,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,air_ba937bf13d40fb24,2016-02-17,17,0,2,17,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,air_ba937bf13d40fb24,2016-02-18,22,0,2,18,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284097,air_fff68b929994bfbd,2017-05-02,0,0,5,2,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284098,air_fff68b929994bfbd,2017-05-03,0,1,5,3,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284099,air_fff68b929994bfbd,2017-05-04,0,1,5,4,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284100,air_fff68b929994bfbd,2017-05-05,0,1,5,5,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284101,air_fff68b929994bfbd,2017-05-06,0,0,5,6,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284102,air_fff68b929994bfbd,2017-05-07,0,0,5,7,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284103,air_fff68b929994bfbd,2017-05-08,0,0,5,8,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284104,air_fff68b929994bfbd,2017-05-09,0,0,5,9,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284105,air_fff68b929994bfbd,2017-05-10,0,0,5,10,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284106,air_fff68b929994bfbd,2017-05-11,0,0,5,11,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284107,air_fff68b929994bfbd,2017-05-12,0,0,5,12,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284108,air_fff68b929994bfbd,2017-05-13,0,0,5,13,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284109,air_fff68b929994bfbd,2017-05-14,0,0,5,14,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284110,air_fff68b929994bfbd,2017-05-15,0,0,5,15,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284111,air_fff68b929994bfbd,2017-05-16,0,0,5,16,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284112,air_fff68b929994bfbd,2017-05-17,0,0,5,17,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284113,air_fff68b929994bfbd,2017-05-18,0,0,5,18,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284114,air_fff68b929994bfbd,2017-05-19,0,0,5,19,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284115,air_fff68b929994bfbd,2017-05-20,0,0,5,20,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284116,air_fff68b929994bfbd,2017-05-21,0,0,5,21,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284117,air_fff68b929994bfbd,2017-05-22,0,0,5,22,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284118,air_fff68b929994bfbd,2017-05-23,0,0,5,23,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284119,air_fff68b929994bfbd,2017-05-24,0,0,5,24,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284120,air_fff68b929994bfbd,2017-05-25,0,0,5,25,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284121,air_fff68b929994bfbd,2017-05-26,0,0,5,26,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284122,air_fff68b929994bfbd,2017-05-27,0,0,5,27,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284123,air_fff68b929994bfbd,2017-05-28,0,0,5,28,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284124,air_fff68b929994bfbd,2017-05-29,0,0,5,29,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284125,air_fff68b929994bfbd,2017-05-30,0,0,5,30,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
284126,air_fff68b929994bfbd,2017-05-31,0,0,5,31,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [94]:
total_dataset.to_csv('total_dataset.csv', encoding='utf-8', index=False)

In [95]:
temp = pd.get_dummies(total_dataset['air_store_id'])
total_dataset = pd.concat([total_dataset,temp],axis=1)
total_dataset.head()

,air_store_id,visit_date,visitors,holiday_flg,month,day,Asian,Bar/Cocktail,Cafe/Sweets,Creative cuisine,...,air_fd6aac1043520e83,air_fdc02ec4a3d21ea4,air_fdcfef8bd859f650,air_fe22ef5a9cbef123,air_fe58c074ec1445ea,air_fea5dc9594450608,air_fee8dcf4d619598e,air_fef9ccb3ba0da2f7,air_ffcc2d5087e1b476,air_fff68b929994bfbd
0,air_ba937bf13d40fb24,2016-01-13,25,0,1,13,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,air_ba937bf13d40fb24,2016-01-14,32,0,1,14,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,air_ba937bf13d40fb24,2016-01-15,29,0,1,15,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,air_ba937bf13d40fb24,2016-01-16,22,0,1,16,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,air_ba937bf13d40fb24,2016-01-18,6,0,1,18,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [97]:
col = [c for c in total_dataset if c not in ['air_store_id', 'visit_date', 'visitors']]
col

['holiday_flg',
 'month',
 'day',
 'Asian',
 'Bar/Cocktail',
 'Cafe/Sweets',
 'Creative cuisine',
 'Dining bar',
 'International cuisine',
 'Italian/French',
 'Izakaya',
 'Japanese food',
 'Karaoke/Party',
 'Okonomiyaki/Monja/Teppanyaki',
 'Other',
 'Western food',
 'Yakiniku/Korean food',
 'Fukuoka-ken Fukuoka-shi Daimyō',
 'Fukuoka-ken Fukuoka-shi Hakata Ekimae',
 'Fukuoka-ken Fukuoka-shi Imaizumi',
 'Fukuoka-ken Fukuoka-shi Momochi',
 'Fukuoka-ken Fukuoka-shi Shiobaru',
 'Fukuoka-ken Fukuoka-shi Takatori',
 'Fukuoka-ken Fukuoka-shi Tenjin',
 'Fukuoka-ken Fukuoka-shi Torikai',
 'Fukuoka-ken Itoshima-shi Maebarunishi',
 'Fukuoka-ken Kitakyūshū-shi Konyamachi',
 'Fukuoka-ken Kitakyūshū-shi None',
 'Fukuoka-ken Kitakyūshū-shi Ōtemachi',
 'Fukuoka-ken Kurume-shi Jōnanmachi',
 'Fukuoka-ken Yame-shi Motomachi',
 'Hiroshima-ken Fukuyama-shi Higashisakuramachi',
 'Hiroshima-ken Hiroshima-shi Kokutaijimachi',
 'Hiroshima-ken Hiroshima-shi Nagarekawachō',
 'Hokkaidō Abashiri-shi Minami 6 Jōhigashi',
 'Hokkaidō Asahikawa-shi 6 Jōdōri',
 'Hokkaidō Katō-gun Motomachi',
 'Hokkaidō Sapporo-shi Atsubetsuchūō 1 Jō',
 'Hokkaidō Sapporo-shi Kita 24 Jōnishi',
 'Hokkaidō Sapporo-shi Kotoni 2 Jō',
 'Hokkaidō Sapporo-shi Minami 3 Jōnishi',
 'Hyōgo-ken Amagasaki-shi Higashinanamatsuchō',
 'Hyōgo-ken Himeji-shi Yasuda',
 'Hyōgo-ken Kakogawa-shi Kakogawachō Kitazaike',
 'Hyōgo-ken Kōbe-shi Kumoidōri',
 'Hyōgo-ken Kōbe-shi Motomachidōri',
 'Hyōgo-ken Kōbe-shi Sumiyoshi Higashimachi',
 'Hyōgo-ken Nishinomiya-shi Rokutanjichō',
 'Hyōgo-ken Takarazuka-shi Tōyōchō',
 'Miyagi-ken Sendai-shi Kamisugi',
 'Niigata-ken Kashiwazaki-shi Chūōchō',
 'Niigata-ken Nagaoka-shi Ōtedōri',
 'Niigata-ken Niigata-shi Gakkōchōdōri 1 Banchō',
 'Niigata-ken Niigata-shi Teraohigashi',
 'Shizuoka-ken Hamamatsu-shi Motoshirochō',
 'Shizuoka-ken Numazu-shi Miyukichō',
 'Shizuoka-ken Shizuoka-shi Ōtemachi',
 'Tōkyō-to Adachi-ku Chūōhonchō',
 'Tōkyō-to Bunkyō-ku Kasuga',
 'Tōkyō-to Bunkyō-ku Sendagi',
 'Tōkyō-to Chiyoda-ku Kanda Jinbōchō',
 'Tōkyō-to Chiyoda-ku Kudanminami',
 'Tōkyō-to Chūō-ku Ginza',
 'Tōkyō-to Chūō-ku Tsukiji',
 'Tōkyō-to Edogawa-ku Chūō',
 'Tōkyō-to Fuchū-shi Miyanishichō',
 'Tōkyō-to Itabashi-ku Itabashi',
 'Tōkyō-to Katsushika-ku Tateishi',
 'Tōkyō-to Kita-ku Ōjihonchō',
 'Tōkyō-to Koganei-shi Honchō',
 'Tōkyō-to Kōtō-ku Kameido',
 'Tōkyō-to Kōtō-ku Tomioka',
 'Tōkyō-to Kōtō-ku Tōyō',
 'Tōkyō-to Machida-shi Morino',
 'Tōkyō-to Meguro-ku Jiyūgaoka',
 'Tōkyō-to Meguro-ku Kamimeguro',
 'Tōkyō-to Meguro-ku Takaban',
 'Tōkyō-to Minato-ku Akasaka',
 'Tōkyō-to Minato-ku Roppongi',
 'Tōkyō-to Minato-ku Shibakōen',
 'Tōkyō-to Musashino-shi Kichijōji Honchō',
 'Tōkyō-to Musashino-shi Midorichō',
 'Tōkyō-to Nakano-ku Nakano',
 'Tōkyō-to Nerima-ku Toyotamakita',
 'Tōkyō-to Setagaya-ku Kitazawa',
 'Tōkyō-to Setagaya-ku Okusawa',
 'Tōkyō-to Setagaya-ku Sangenjaya',
 'Tōkyō-to Setagaya-ku Setagaya',
 'Tōkyō-to Shibuya-ku Dōgenzaka',
 'Tōkyō-to Shibuya-ku Higashi',
 'Tōkyō-to Shibuya-ku Jingūmae',
 'Tōkyō-to Shibuya-ku Shibuya',
 'Tōkyō-to Shinagawa-ku Higashigotanda',
 'Tōkyō-to Shinagawa-ku Hiromachi',
 'Tōkyō-to Shinjuku-ku Kabukichō',
 'Tōkyō-to Shinjuku-ku Nishishinjuku',
 'Tōkyō-to Suginami-ku Asagayaminami',
 'Tōkyō-to Tachikawa-shi Izumichō',
 'Tōkyō-to Taitō-ku Asakusa',
 'Tōkyō-to Taitō-ku Higashiueno',
 'Tōkyō-to Taitō-ku Kuramae',
 'Tōkyō-to Toshima-ku Higashiikebukuro',
 'Tōkyō-to Toshima-ku Mejiro',
 'Tōkyō-to Toshima-ku Minamiikebukuro',
 'Tōkyō-to Toshima-ku Nishiikebukuro',
 'Tōkyō-to Toshima-ku Sugamo',
 'Tōkyō-to Ōta-ku Kamata',
 'Tōkyō-to Ōta-ku Kamiikedai',
 'Ōsaka-fu Higashiōsaka-shi Aramotokita',
 'Ōsaka-fu Neyagawa-shi Honmachi',
 'Ōsaka-fu Sakai-shi Minamikawaramachi',
 'Ōsaka-fu Suita-shi Izumichō',
 'Ōsaka-fu Ōsaka-shi Fuminosato',
 'Ōsaka-fu Ōsaka-shi Kyōmachibori',
 'Ōsaka-fu Ōsaka-shi Kyūtarōmachi',
 'Ōsaka-fu Ōsaka-shi Nakanochō',
 'Ōsaka-fu Ōsaka-shi Nanbasennichimae',
 'Ōsaka-fu Ōsaka-shi Shinmachi',
 'Ōsaka-fu Ōsaka-shi Ōgimachi',
 'Ōsaka-fu Ōsaka-shi Ōhiraki',
 'Friday',
 'Monday',
 'Saturday',
 'Sunday',
 'Thursday',
 'Tuesday',
 'Wednesday',
 2016,
 2017,
 'loc_-1',
 'loc_0',
 'loc_1',
 'loc_2',
 'loc_3',
 'loc_4',
 'loc_5',
 'loc_6',
 'loc_7',
 'loc_8',
 'loc_9',
 'loc_10',
 'loc_11',
 'loc_12',
 'loc_13',
 'loc_14',
 'loc_15',
 'loc_16',
 'loc_17',
 'loc_18',
 'loc_19',
 'loc_20',
 'loc_21',
 'loc_22',
 'loc_23',
 'air_00a91d42b08b08d9',
 'air_0164b9927d20bcc3',
 'air_0241aa3964b7f861',
 'air_0328696196e46f18',
 'air_034a3d5b40d5b1b1',
 'air_036d4f1ee7285390',
 'air_0382c794b73b51ad',
 'air_03963426c9312048',
 'air_04341b588bde96cd',
 'air_049f6d5b402a31b2',
 'air_04cae7c1bc9b2a0b',
 'air_0585011fa179bcce',
 'air_05c325d315cc17f5',
 'air_0647f17b4dc041c8',
 'air_064e203265ee5753',
 'air_066f0221b8a4d533',
 'air_06f95ac5c33aca10',
 'air_0728814bd98f7367',
 'air_0768ab3910f7967f',
 'air_07b314d83059c4d2',
 'air_07bb665f9cdfbdfb',
 'air_082908692355165e',
 'air_083ddc520ea47e1e',
 'air_0845d8395f30c6bb',
 'air_084d98859256acf0',
 'air_0867f7bebad6a649',
 'air_08ba8cd01b3ba010',
 'air_08cb3c4ee6cd6a22',
 'air_08ef81d5b7a0d13f',
 'air_08f994758a1e76d4',
 'air_09040f6df960ddb8',
 'air_0919d54f0c9a24b8',
 'air_09661c0f3259cc04',
 'air_09a845d5b5944b01',
 'air_09fd1f5c58583141',
 'air_0a74a5408a0b8642',
 'air_0b184ec04c741a6a',
 'air_0b1e72d2d4422b20',
 'air_0b9038300f8b2b50',
 'air_0e1eae99b8723bc1',
 'air_0e7c11b9abc50163',
 'air_0ead98dd07e7a82a',
 'air_0f0cdeee6c9bf3d7',
 'air_0f2f96335f274801',
 'air_0f60e1576a7d397d',
 'air_1033310359ceeac1',
 'air_10393f12e9069760',
 'air_105a7954e32dba9b',
 'air_10713fbf3071c361',
 'air_10bbe8acd943d8f6',
 'air_12c4fb7a423df20d',
 'air_138ee734ac79ff90',
 'air_138ff410757b845f',
 'air_1408dd53f31a8a65',
 'air_142e78ba7001da9c',
 'air_1509881b22965b34',
 'air_152c1f08d7d20e07',
 'air_15ae33469e9ea2dd',
 'air_15e6e15c7ea2c162',
 'air_16179d43b6ee5fd8',
 'air_1653a6c513865af3',
 'air_168441ada3e878e1',
 'air_16c4cfddeb2cf69b',
 'air_16cf0a73233896de',
 'air_1707a3f18bb0da07',
 'air_17a6ab40f97fd4d8',
 'air_17bed6dbf7c8b0fc',
 'air_1979eaff8189d086',
 'air_1ab60ce33bfed8a8',
 'air_1ae94f514a0bce13',
 'air_1ba4e87ef7422183',
 'air_1c0b150f9e696a5f',
 'air_1c95a84924d72500',
 'air_1d1e8860ae04f8e9',
 'air_1d25ca6c76df48b4',
 'air_1d3f797dd1f7cf1c',
 'air_1dd8f6f47480d1a2',
 'air_1dea9815ccd36620',
 'air_1e23210b584540e7',
 'air_1e665503b8474c55',
 'air_1eeff462acb24fb7',
 'air_1f1390a8be2272b3',
 'air_1f34e9beded2231a',
 'air_1f7f8fa557bc0d55',
 'air_2009041dbf9264de',
 'air_20619d21192aa571',
 'air_20add8092c9bb51d',
 'air_2195cd5025a98033',
 'air_21f5052d5330528d',
 'air_220cba70c890b119',
 'air_22682e965418936f',
 'air_228f10bec0bda9c8',
 'air_229d7e508d9f1b5e',
 'air_232dcee6f7c51d37',
 'air_234d3dbf7f3d5a50',
 'air_23e1b11aee2a1407',
 'air_23ee674e91469086',
 'air_24b9b2a020826ede',
 'air_24e8414b9b07decb',
 'air_2545dd3a00f265e2',
 'air_256be208a979e023',
 'air_2570ccb93badde68',
 'air_258ad2619d7bff9a',
 'air_258dc112912fc458',
 'air_25c583983246b7b0',
 'air_25d8e5cc57dd87d9',
 'air_25e9888d30b386df',
 'air_2634e41551e9807d',
 'air_26c5bbeb7bb82bf1',
 'air_26f10355d9b4d82a',
 'air_2703dcb33192b181',
 'air_275732a5db46f4d3',
 'air_27e991812b0d9c92',
 'air_28064154614b2e6c',
 'air_287d2de7d3c93406',
 'air_28a9fa1ec0839375',
 'air_28dbe91c4c9656be',
 'air_290e7a57b390f78e',
 'air_298513175efdf261',
 'air_2a184c1745274b2b',
 'air_2a24aec099333f39',
 'air_2a3743e37aab04b4',
 'air_2a485b92210c98b5',
 'air_2a7f14da7fe0f699',
 'air_2aab19554f91ff82',
 'air_2ac361b97630e2df',
 'air_2b8b29ddfd35018e',
 'air_2b9bc9f5f5168ea1',
 'air_2bffb19a24d11729',
 'air_2c505f9ad67d4635',
 'air_2c6c79d597e48096',
 'air_2c6fef1ce0e13a5a',
 'air_2c989829acbd1c6b',
 'air_2cee51fa6fdf6c0d',
 'air_2d3afcb91762fe01',
 'air_2d78d9a1f4dd02ca',
 'air_2e7cb1f1a2a9cd6a',
 'air_2f8ced25216df926',
 'air_2fc149abe33adcb4',
 'air_2fc478dc9f0a6b31',
 'air_2fed81034f8834e5',
 'air_303bac187b53083a',
 'air_310e467e6e625004',
 'air_3155ee23d92202da',
 'air_31c753b48a657b6c',
 'air_32460819c7600037',
 'air_324f7c39a8410e7c',
 'air_326ca454ef3558bc',
 'air_32b02ba5dc2027f4',
 'air_32c61b620a766138',
 'air_32f5d7cd696e3c4a',
 'air_33b01025210d6007',
 'air_3440e0ea1b70a99b',
 'air_346ade7d29230634',
 'air_347be2c4feeb408b',
 'air_349278fa964bb12f',
 'air_3525f11ef0bf0c35',
 'air_35512c42db0868da',
 'air_3561fd1c0bce6a95',
 'air_35c4732dcbfe31be',
 'air_36429b5ca4407b3e',
 'air_36bcf77d3382d36e',
 'air_37189c92b6c761ec',
 'air_375a5241615b5e22',
 'air_382f5ace4e2247b8',
 'air_383f5b2f8d345a49',
 'air_38746ffe9aa20c7e',
 'air_396166d47733d5c9',
 'air_396942e6423a2145',
 'air_397d3f32a7196aa2',
 'air_3980af67be35afdb',
 'air_3982a2c4ea2ed431',
 'air_399904bdb7685ca0',
 'air_39dccf7df20b1c6a',
 'air_3a8a3f8fb5cd7f88',
 'air_3aa839e8e0cb6c87',
 'air_3ac24136722e2291',
 'air_3b20733899b5287f',
 'air_3b6438b125086430',
 'air_3bb99a1fe0583897',
 'air_3bd49f98ab7f36ab',
 'air_3c05c8f26c611eb9',
 'air_3c938075889fc059',
 'air_3cad29d1a23209d2',
 'air_3caef3f76b8f26c5',
 'air_3d3a2b509180e798',
 'air_3e6cea17a9d2c0f1',
 'air_3e93f3c81008696d',
 'air_3f91d592acd6cc0b',
 'air_401b39f97e56b939',
 'air_4043b7ccfbffa732',
 'air_4092cfbd95a3ac1b',
 'air_40953e2d8b4f2857',
 'air_40f6193ea3ed1b91',
 'air_414ff459ed18fa48',
 'air_41bbf6e1d9814c4b',
 'air_421670f21da5ba31',
 'air_4254c3fc3ad078bd',
 'air_42c9aa6d617c5057',
 'air_42d41eb58cad170e',
 'air_43b65e4b05bff2d3',
 'air_43d577e0c9460e64',
 'air_4433ab8e9999915f',
 'air_4481a87c1d7c9896',
 'air_452100f5305dde64',
 'air_45326ebb8dc72cfb',
 'air_4570f52104fe0982',
 'air_4579cb0669fd411b',
 'air_457efe8c3a30ea17',
 'air_464a62de0d57be1e',
 'air_465bddfed3353b23',
 'air_47070be6093f123e',
 'air_472b19e3b5bffa41',
 'air_473cf23b9e7c0a37',
 'air_473f98b212d37b4a',
 'air_47beaffd3806c979',
 'air_483eba479dc9910d',
 'air_48e9fc98b62495a7',
 'air_48f4da6223571da4',
 'air_48ffd31594bc3263',
 'air_49211568cab5fdee',
 'air_4974785f48853db9',
 'air_4b251b9f8373f1ae',
 'air_4b380b4db9d37883',
 'air_4b55d8aea1d2b395',
 'air_4b9085d0d46a6211',
 'air_4beac252540f865e',
 'air_4c2ed28f3f19ca52',
 'air_4c665a2bfff0da3b',
 'air_4c727b55acdee495',
 'air_4cab15ad29c0ffbc',
 'air_4cab91146e3d1897',
 'air_4cca5666eaf5c709',
 'air_4ce7b17062a1bf73',
 'air_4d21676ed11f0bac',
 'air_4d71826793c09b22',
 'air_4d90a22572fa1ec9',
 'air_4de6d887a7b1c1fc',
 'air_4dea8d17f6f59c56',
 'air_4e1c38f68f435596',
 'air_4f762e840b3996e1',
 'air_4feeb8600f131e43',
 'air_500641aca4cf673c',
 'air_506fe758114df773',
 'air_51281cd059d7b89b',
 'air_51319e7acf0438cf',
 'air_52a08ef3efdb4bb0',
 'air_52e2a1fd42bc917a',
 'air_536043fcf1a4f8a4',
 'air_539d693f7317c62d',
 'air_546b353cbea4a45b',
 'air_5485912b44f976de',
 'air_54d6c25d33f5260e',
 'air_54ed43163b7596c4',
 'air_55390f784018349a',
 'air_55c3627912b9c849',
 'air_55e11c33d4758131',
 'air_56cd12f31a0afc04',
 'air_56cebcbd6906e04c',
 'air_56ea46c14b2dd967',
 'air_57013002b912772b',
 'air_573ecdf81b157d22',
 'air_57c9eea1a2b66e65',
 'air_57ed725a1930a5b9',
 'air_5878b6f2a9da12c1',
 'air_59cc9b2b209c6331',
 'air_5a9a6cbeeb434c08',
 'air_5acc13d655a6e8b2',
 'air_5afb1cca48ceaa19',
 'air_5b6d18c470bbfaf9',
 'air_5b704df317ed1962',
 'air_5bd22f9cc1426a90',
 'air_5c65468938c07fa5',
 'air_5c7489c9ec755e2d',
 'air_5c817ef28f236bdf',
 'air_5cb030b9f0b91537',
 'air_5cfc537125d97f16',
 'air_5d7c744c3a2ef624',
 'air_5d945ade487cdf4d',
 'air_5dea8a7a5bf5eb71',
 'air_5e339a1f364cdb00',
 'air_5e34c6fe6fabd10e',
 'air_5e70fe82f9e4fab6',
 'air_5e939e005bd34633',
 'air_5ed3198e4a5eed0f',
 'air_5f3a3ef4cba110a4',
 'air_5f6fa1b897fe80d5',
 'air_5fbda8e9302f7c13',
 'air_602ca92c0db34f8f',
 'air_609050e4e4f79ae1',
 'air_60a7057184ec7ec7',
 'air_60aa54ecbc602348',
 'air_6108821ffafa9b72',
 'air_614e2f7e76dff854',
 'air_61668cc2b0778898',
 'air_61b8d37c33617f21',
 'air_61de73b097513f58',
 'air_622375b4815cf5cb',
 'air_627cabe2fe53f33f',
 'air_629d9935273c82ae',
 'air_629edf21ea38ac2d',
 'air_632ba66e1f75aa28',
 'air_638c35eb25e53eea',
 'air_63a750d8b4b6a976',
 'air_63a88d81295195ed',
 'air_63b13c56b7201bd9',
 'air_63e28ee0b0c955a7',
 'air_640cf4835f0d9ba3',
 'air_6411203a47b5ec77',
 'air_645cb18b33f938cf',
 'air_646b93e336f0dded',
 'air_64a5d5c1381837af',
 'air_64d4491ad8cdb1c6',
 'air_650f9b9de0c5542c',
 'air_657a0748462f85de',
 'air_65e294f1ae6df9c3',
 'air_6607fe3671242ce3',
 'air_670a0c1c4108bcea',
 'air_671b4bea84dafb67',
 'air_673acd9fa5e0dd78',
 'air_67483104fa38ef6c',
 'air_675aa35cba456fd1',
 'air_67f87c159d9e2ee2',
 'air_68147db09287bf74',
 'air_681b0c56328dd2af',
 'air_681f96e6a6595f82',
 'air_68301bcb11e2f389',
 'air_683371d9baabf410',
 'air_6836438b543ba698',
 'air_6873982b9e19c7ad',
 'air_68c1de82037d87e6',
 'air_68cc910e7b307b09',
 'air_68d075113f368946',
 'air_6902e4ec305b3d08',
 'air_694571ea13fb9e0e',
 'air_6a15e4eae523189d',
 'air_6b15edd1b4fbb96a',
 'air_6b2268863b14a2af',
 'air_6b65745d432fd77f',
 'air_6b7678aae65d2d59',
 'air_6b942d5ebbc759c2',
 'air_6b9fa44a9cf504a1',
 'air_6c1128955c58b690',
 'air_6c91a28278a16f64',
 'air_6c952e3c6e590945',
 'air_6ca1d941c8199a67',
 'air_6cbe54f0aa30b615',
 'air_6ced51c24fb54262',
 'air_6d64dba2edd4fc0c',
 'air_6d65542aa43b598b',
 'air_6d65dd11d96e00fb',
 'air_6e06824d0934dd81',
 'air_6e3fd96320d24324',
 'air_6e64fb5821402cd2',
 'air_6ff5fca957798daa',
 'air_707d4b6328f2c2df',
 'air_709262d948dd0b6e',
 'air_70e9e8cd55879414',
 'air_70f834596eb99fee',
 'air_710d6537cb7623df',
 'air_712dd258f7f91b4b',
 'air_71903025d39a4571',
 'air_722297e7f26db91d',
 'air_728ff578acc6ac6e',
 'air_72f5146cf0c49beb',
 'air_735bcbe1763d6e98',
 'air_73f316e6a18d8aa9',
 'air_7420042ff75f9aca',
 'air_746211c0b532e8aa',
 'air_747f375eb3900e1e',
 'air_74cf22153214064c',
 'air_7514d90009613cd6',
 'air_754ae581ad80cc9f',
 'air_75864c80d2fb334a',
 'air_75bd5d1b6dc6670d',
 'air_764f71040a413d4d',
 'air_77488fa378cf98c3',
 'air_77dfc83450cbc89c',
 'air_7831b00996701c0f',
 'air_789103bf53b8096b',
 'air_789466e488705c93',
 'air_78df4dc6a7e83e41',
 'air_79afb3f52b4d062c',
 'air_79f528087f49df06',
 'air_7a81bd7fadcbf3d8',
 'air_7a946aada80376a4',
 'air_7bacc4d36fb094c9',
 'air_7bc6ca04d7b0f3b8',
 'air_7bda6048a4a78837',
 'air_7c7774c66fb237f7',
 'air_7cc17a324ae5c7dc',
 'air_7cf5a02c0e01b647',
 'air_7d65049f9d275c0d',
 'air_7dacea2f22afccfb',
 'air_7db266904cb0d72a',
 'air_7e12c5d27f44a8de',
 'air_7ef9a5ea5c8fe39f',
 'air_7f3dc18494bce98b',
 'air_7f9e15afafcf4c75',
 'air_7fbf7649eb13ad9b',
 'air_800c02226e2e0288',
 'air_8093d0b565e9dbdf',
 'air_8110d68cc869b85e',
 'air_81546875de9c8e78',
 'air_81a12d67c22e012f',
 'air_81bd68142db76f58',
 'air_81c2600146d07d16',
 'air_81c5dff692063446',
 'air_820d1919cbecaa0a',
 'air_82a6ae14151953ba',
 'air_831658500aa7c846',
 'air_832f9dbe9ee4ebd3',
 'air_83db5aff8f50478e',
 'air_84060403939d8216',
 'air_848616680ef061bd',
 'air_84f6876ff7e83ae7',
 'air_8523d6a70de49e6c',
 'air_859feab8e3c9f98d',
 'air_85bd13a49370c392',
 'air_86cfbf2624576fad',
 'air_86f7b2109e4abd65',
 'air_87059630ab6fe47f',
 'air_87078cf7903a648c',
 'air_87467487d21891dd',
 'air_8764b3473ddcceaf',
 'air_876d7a23c47811cb',
 'air_877f79706adbfb06',
 'air_87ca98aa7664de94',
 'air_87f9e1024b951f01',
 'air_883ca28ef0ed3d55',
 'air_88c8e34baa79217b',
 'air_88ca84051ba95339',
 'air_88f31db64991768a',
 'air_890d7e28e8eaaa11',
 'air_89e7328af22efe74',
 'air_8a1d21fad48374e8',
 'air_8a59bb0c497b771e',
 'air_8a906e5801eac81c',
 'air_8b4a46dc521bfcfe',
 'air_8c119d1f16049f20',
 'air_8c3175aa5e4fc569',
 'air_8cc350fd70ee0757',
 'air_8ce035ee1d8a56a6',
 'air_8d50c64692322dff',
 'air_8d61f49aa0373492',
 'air_8e429650fcf7a0ae',
 'air_8e4360a64dbd4c50',
 'air_8e492076a1179383',
 'air_8e8f42f047537154',
 'air_8ec47c0f1e2c879e',
 'air_8f13ef0f5e8c64dd',
 'air_8f273fb9ad2fed6f',
 'air_8f3b563416efc6ad',
 'air_900d755ebd2f7bbd',
 'air_901925b628677c2e',
 'air_90213bcae4afa274',
 'air_90bd5de52c166767',
 'air_90ed0a2f24755533',
 'air_90f0efbb702d77b7',
 'air_9105a29b0eb250d2',
 'air_91236b89d29567af',
 'air_9152d9926e5c4a3a',
 'air_915558a55c2bc56c',
 'air_91beafbba9382b0a',
 'air_91d72e16c4bcba55',
 'air_9241121af22ff1d6',
 'air_929d8513e3cdb423',
 'air_931a8a4321b6e7d1',
 'air_9352c401d5adb01b',
 'air_9387ff95e886ebc7',
 'air_938ef91ecdde6878',
 'air_939964477035ef0b',
 'air_93b9bb641f8fc982',
 'air_93dd7070c9bf5453',
 'air_93ebe490d4abb8e9',
 'air_9438d67241c81314',
 'air_947eb2cae4f3e8f2',
 'air_9483d65e9cc9a6b7',
 'air_950381108f839348',
 'air_95d28905941fd4cb',
 'air_95e917913cd988f3',
 'air_96005f79124e12bf',
 'air_965b2e0cf4119003',
 'air_96743eee94114261',
 'air_96773a6236d279b1',
 'air_968d72c12eed09f0',
 'air_96929a799b12a43e',
 'air_96ec3cfe78cb0652',
 'air_97159fc4e90053fe',
 'air_97958e7fce98b6a3',
 'air_97b2a9f975fc702c',
 'air_97cf68dc1a9beac0',
 'air_97e0f2feec4d577a',
 'air_9828505fefc77d75',
 'air_98b54e32ccddd896',
 'air_990a642a3deb2903',
 'air_99157b6163835eec',
 'air_99a5183695b849f9',
 'air_99b01136f451fc0e',
 'air_99c3eae84130c1cb',
 'air_9a30407764f4ff84',
 'air_9a6f6e7f623003d2',
 'air_9aa32b3db0fab3a5',
 'air_9aa92007e3628dbc',
 'air_9ae7081cb77dc51e',
 'air_9b13c7feb0a0c431',
 'air_9b6af3db40da4ae2',
 'air_9bbc673495e23532',
 'air_9bf0ccac497c4af3',
 'air_9bf595ef095572fb',
 'air_9c6787aa03a45586',
 'air_9ca2767761efff4d',
 'air_9cd5e310f488bced',
 'air_9cf2f1ba86229773',
 'air_9d3482b4680aee88',
 'air_9d452a881f7f2bb7',
 'air_9d474ec2448c700d',
 'air_9d5a980b211e1795',
 'air_9d93d95720f2e831',
 'air_9dc9483f717d73ee',
 'air_9dd7d38b0f1760c4',
 'air_9e920b758503ef54',
 'air_9efaa7ded03c5a71',
 'air_9f277fb7a2c1d842',
 'air_9fc607777ad76b26',
 'air_a083834e7ffe187e',
 'air_a11473cc1eb9a27f',
 'air_a17f0778617c76e2',
 'air_a1fe8c588c8d2f30',
 'air_a218912784bf767d',
 'air_a21ffca0bea1661a',
 'air_a239a44805932bab',
 'air_a24bf50c3e90d583',
 'air_a2567267116a3b75',
 'air_a257c9749d8d0ff6',
 'air_a271c9ba19e81d17',
 'air_a2b29aa7feb4e36f',
 'air_a304330715435390',
 'air_a33461f4392ec62c',
 'air_a373500730e2a9e0',
 'air_a38f25e3399d1b25',
 'air_a41b032371a63427',
 'air_a49f1cf0634f13e5',
 'air_a510dcfe979f09eb',
 'air_a546cbf478a8b6e4',
 'air_a55d17bd3f3033cb',
 'air_a563896da3777078',
 'air_a678e5b144ca24ce',
 'air_a7404a854919e990',
 'air_a8533b7a992bb0ca',
 'air_a85f0c0c889f6b7e',
 'air_a85f8c0bfd61889f',
 'air_a88ac559064dec08',
 'air_a9133955abccf071',
 'air_a9178f19da58fe99',
 'air_a9a380530c1e121f',
 'air_aa0049fe3cc6f4d6',
 'air_ab3ae0e410b20069',
 'air_ab9746a0f83084b7',
 'air_abcdc8115988a010',
 'air_abf06fcca748dca5',
 'air_ac7a7427c9ae12a5',
 'air_ad13e71e21235131',
 'air_ad60f6b76c9df7ed',
 'air_ad7777590c884721',
 'air_add9a575623726c8',
 'air_ade6e836ffd1da64',
 'air_aed3a8b49abe4a48',
 'air_af03c277a167b2bd',
 'air_af24e3e817dea1e5',
 'air_af63df35857b16e6',
 'air_b0a6a4c5e95c74cf',
 'air_b162fb07fbbdea33',
 'air_b192fb5310436005',
 'air_b1a72bf1ebf4b8ef',
 'air_b1bb1fae86617d7a',
 'air_b1d822f75c9fc615',
 'air_b2395df0e874078d',
 'air_b23d0f519291247d',
 'air_b259b4e4a51a690d',
 'air_b28bed4b2e7167b7',
 'air_b2a639cc7e02edf1',
 'air_b2d8bc9c88b85f96',
 'air_b2d97bd2337c5ba7',
 'air_b2dcec37b83e2494',
 'air_b30fffd7ab1e75a5',
 'air_b3180b74332ba886',
 'air_b3a824511477a4ed',
 'air_b439391e72899756',
 'air_b45b8e456f53942a',
 'air_b4f32bcc399da2b9',
 'air_b5598d12d1b84890',
 'air_b5bdd318005d9aa4',
 'air_b60cc7d6aee68194',
 'air_b711b43ae472cb6b',
 'air_b7fa3d2fca744dd2',
 'air_b80fed1a07c817d2',
 'air_b88192b35ac03c24',
 'air_b8925441167c3152',
 'air_b8a5ee69e5fdcc5b',
 'air_b8d9e1624baaadc2',
 'air_b9e27558fb8bd5c4',
 'air_ba495cccc8f0f237',
 'air_ba937bf13d40fb24',
 'air_bac5f4441db21db9',
 'air_baf28ac9f13a307d',
 'air_bb09595bab7d5cfb',
 'air_bb26d6d079594414',
 'air_bb4ff06cd661ee9b',
 'air_bbe1c1a47e09f161',
 'air_bc991c51d6613745',
 'air_bc9a129e11a2efe0',
 'air_bcce1ea4350b7b72',
 'air_bd74a9222edfdfe1',
 'air_bdd32aa407c16335',
 'air_bebd55ed63ab2422',
 'air_bed603c423b7d9d4',
 'air_bedd35489e666605',
 'air_bf13014b6e3e60ca',
 'air_bf21b8350771879b',
 'air_bf617aa68d5f1cfa',
 'air_bf7591560077332d',
 'air_bfafaed35e213fd7',
 'air_bfda7731a6c6fc61',

In [98]:
sep = len(df['air_visit_data'])
train = total_dataset[:sep]
to_predict = total_dataset[sep:]
print(len(train))
print(len(to_predict))

252108
32019

In [4]:
train.to_csv('train.csv', encoding='utf-8', index=False)
to_predict.to_csv('to_predict.csv', encoding='utf-8', index=False)

NameError: name 'train' is not defined

In [2]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error
def RMSLE(y, pred):
    return mean_squared_error(y, pred)**0.5 


train = pd.read_csv('train.csv')
to_predict = pd.read_csv('to_predict.csv')
total_dataset = pd.read_csv('total_dataset.csv')
col = [c for c in train if c not in ['air_store_id', 'visit_date', 'visitors']]

In [4]:
X_train, y_train = train[col], train['visitors']
X_to_predict = to_predict[col]
value_X = X_train.values
value_y = y_train.values
value_X_to_predict = X_to_predict.values
print(value_X.shape)
print(value_y.shape)
print(value_X_to_predict.shape)

(252108, 983)
(252108,)
(32019, 983)

In [5]:
from sklearn.preprocessing import MinMaxScaler

scaler_X = MinMaxScaler(feature_range=(0, 1))
scaled_X = scaler_X.fit_transform(value_X)
scaled_X_to_predict = scaler_X.transform(value_X_to_predict)
# scaler_y = MinMaxScaler(feature_range=(0, 1))
# value_y = value_y.reshape((len(value_y), 1))
# scaled_y = scaler_y.fit_transform(value_y)

C:\Users\lei\Anaconda3\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)

In [6]:
from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(scaled_X, value_y, test_size=0.3, random_state=42)

C:\Users\lei\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [11]:
# Initial Setup for Keras
from keras.models import Sequential
from keras import optimizers, regularizers
from keras.layers import Dense, Input, Activation, Dropout

# TODO: Build the Neural Network in Keras Here
model = Sequential()
model.add(Dense(512, activation = 'relu', input_shape=(983,)))
model.add(Dense(128, activation='relu'))
model.add(Dense(32, activation='relu'))
# model.add(Dropout(0.5))
# model.add(Dense(128, activation = 'tanh'))
# model.add(Dense(64, activation = 'sigmoid', kernel_regularizer=regularizers.l2(0.01)))
model.add(Dense(1, activation='relu'))


sgd = optimizers.SGD(lr=0.005, decay=1e-6, momentum=0.9, nesterov=False)

model.compile(loss='mean_squared_error', optimizer=sgd)

for l in model.layers:
    print(l.name, l.input_shape, l.output_shape)

dense_4 (None, 983) (None, 512)
dense_5 (None, 512) (None, 128)
dense_6 (None, 128) (None, 32)
dense_7 (None, 32) (None, 1)

In [12]:
history = model.fit(X_train, np.log1p(y_train), batch_size = 128, nb_epoch=20,
                    validation_data=(X_test, np.log1p(y_test)), verbose=1)

Train on 176475 samples, validate on 75633 samples
Epoch 1/20
176475/176475 [==============================] - 46s - loss: 0.5017 - val_loss: 0.3323
Epoch 2/20
176475/176475 [==============================] - 40s - loss: 0.3222 - val_loss: 0.3039
Epoch 3/20
176475/176475 [==============================] - 40s - loss: 0.3006 - val_loss: 0.2941
Epoch 4/20
176475/176475 [==============================] - 39s - loss: 0.2884 - val_loss: 0.2838
Epoch 5/20
176475/176475 [==============================] - 39s - loss: 0.2793 - val_loss: 0.2958
Epoch 6/20
176475/176475 [==============================] - 39s - loss: 0.2742 - val_loss: 0.2845
Epoch 7/20
176475/176475 [==============================] - 40s - loss: 0.2694 - val_loss: 0.2941
Epoch 8/20
176475/176475 [==============================] - 40s - loss: 0.2654 - val_loss: 0.2736
Epoch 9/20
176475/176475 [==============================] - 41s - loss: 0.2622 - val_loss: 0.2757
Epoch 10/20
176475/176475 [==============================] - 39s - loss: 0.2587 - val_loss: 0.2745
Epoch 11/20
176475/176475 [==============================] - 39s - loss: 0.2556 - val_loss: 0.2682
Epoch 12/20
176475/176475 [==============================] - 38s - loss: 0.2530 - val_loss: 0.2696
Epoch 13/20
176475/176475 [==============================] - 38s - loss: 0.2509 - val_loss: 0.2669
Epoch 14/20
176475/176475 [==============================] - 38s - loss: 0.2496 - val_loss: 0.2790
Epoch 15/20
176475/176475 [==============================] - 37s - loss: 0.2470 - val_loss: 0.2687
Epoch 16/20
176475/176475 [==============================] - 37s - loss: 0.2448 - val_loss: 0.2719
Epoch 17/20
176475/176475 [==============================] - 37s - loss: 0.2435 - val_loss: 0.2701
Epoch 18/20
176475/176475 [==============================] - 36s - loss: 0.2426 - val_loss: 0.2714
Epoch 19/20
176475/176475 [==============================] - 36s - loss: 0.2405 - val_loss: 0.2714
Epoch 20/20
176475/176475 [==============================] - 36s - loss: 0.2383 - val_loss: 0.2736

In [13]:
y_ = model.predict(X_test)

# yhat_inverse = scaler_y.inverse_transform(yhat.reshape(-1, 1))
# testY_inverse = scaler_y.inverse_transform(y_test.reshape(-1, 1))
y_test = y_test.reshape(-1, 1)
rmsle = RMSLE(np.log1p(y_test), y_)
print(y_test)
print(np.expm1(y_))
print('Test RMSLE: %.3f' % rmsle)

[[33]
 [20]
 [24]
 ...,
 [16]
 [ 5]
 [62]]
[[ 21.47256279]
 [  9.82246685]
 [ 17.87391663]
 ...,
 [ 15.5447197 ]
 [ 19.76002121]
 [ 75.05644226]]
Test RMSLE: 0.523

In [15]:
y_predicted = np.expm1(model.predict(scaled_X_to_predict))

submit = pd.read_csv('sample_submission.csv')

submit['visitors'] = y_predicted

submit.to_csv('to_submit.csv', encoding='utf-8', index=False)